# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(editable=False)),
                ('text', models.CharField(max_length=500)),
                ('trust_level', models.CharField(max_length=20)),
            ],
        ),
    ]
