# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20170325_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='trust_level',
        ),
    ]
