# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_category_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
